all:
  children:
    my_apps:
      vars:
        ansible_port: 22
        ansible_ssh_pass: 'myapp'
        ansible_ssh_user: 'myapp'
        ansible_sudo_pass: 'myapp'
      hosts:
        server1:
          ansible_ssh_host: 192.168.1.202