pipeline {
    agent any
    parameters {
        choice(name: 'SERVER', choices: ['nginx_2'])
        choice(name: 'DETAILS', choices: ['','-v','-vv','-vvv','-vvvv'])
    }

    stages {
        stage('Update NGINX configs') {
            steps {
            withCredentials([sshUserPrivateKey(credentialsId: 'NGINX_SSH_CRED', keyFileVariable: 'PRIVATE')]){
                sh 'ansible-playbook nginx/update_conf_playbook/nginx_conf_playbook.yml -i nginx/hosts.yml -e "host=${SERVER}" --private-key $PRIVATE ${DETAILS}'
                }
            }
        }
    }

    post {
          cleanup {
              cleanWs()
          }
    }
}
