
pipeline {
    agent any
    parameters {
        booleanParam(name: 'UPDATE_JOB_CONF', defaultValue: true, description: 'ОБновить конфигурацию')
        choice(name: 'SERVER', choices: ['nginx_2', 'nginx_1'])
        choice(name: 'DETAILS', choices: ['','-v','-vv','-vvv','-vvvv'])
    }

    stages {
        stage('Update job configuration') {
            when {
                allOf {
                environment name: 'UPDATE_JOB_CONF', value: 'true'
                }
            }
            steps {
                echo 'Update job configuration'
            }
        }
        stage('TEST') {
            when {
                allOf {
                environment name: 'UPDATE_JOB_CONF', value: 'true'
                }
            }
            stages('Update job configuration') {
                stage('st1'){
                   steps {
                    echo 'Update job configuration'
                    }
                }
                stage('st2'){
                   steps {
                    echo 'Update job configuration'
                    }
                }
            }
        }
        stage('Update NGINX configs') {
            when {
                allOf {
                environment name: 'UPDATE_JOB_CONF', value: 'false'
                }
            }
            steps {
            withCredentials([sshUserPrivateKey(credentialsId: 'NGINX_SSH_CRED', keyFileVariable: 'PRIVATE')]){
                sh 'ansible-playbook nginx/update_conf_playbook/nginx_conf_playbook.yml -i nginx/hosts.yml -e "host=${SERVER}" --private-key $PRIVATE ${DETAILS}'
                }
            }
        }
        stage('Example') {
            input {
                message "Should we continue?"
                ok "Yes, we should."
                submitter "alice,bob"
                parameters {
                    string(name: 'PERSON', defaultValue: 'Mr Jenkins', description: 'Who should I say hello to?')
                    booleanParam(name: 'BOOL_PARAM', defaultValue: 'true', description: 'WHAT?')
                }
            }
            steps {
                echo "Hello, ${PERSON}, nice to meet you."
                echo "${BOOL_PARAM}"
            }
        }
    }

    post {
          cleanup {
              cleanWs()
          }
    }
}
