all:
  children:
    nginx:
      vars:
        ansible_port: 22
        ansible_user: "nginx"
        ansible_ssh_private_key_file: "{{ lookup('env', 'NGINX_SSH_CRED') }}"
      hosts:
        nginx_2:
          ansible_ssh_host: 192.168.1.202