---
- hosts: "{{ host }}"
  remote_user: nginx
  tasks:
    - name: Add repository
      command: "sudo systemctl start nginx.service"
      tags: start
    - name: Install the latest version of Postgree
      command: "sudo systemctl stop nginx.service"
      tags: stop